// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  hero: dynamic(() => import("./Hero")),
  product_grid: dynamic(() => import("./ProductGrid")),
  team_grid: dynamic(() => import("./TeamGrid")),
  video_block: dynamic(() => import("./VideoBlock")),
};
